#!/bin/bash 
set -e

if [ -z "${PRESTASHOP_VERSION}" ]
	then PRESTASHOP_VERSION=1.6.1.6;
fi

if [ -z "${PRESTASHOP_LANG}" ]
  then PRESTASHOP_LANG=it;
fi

PRESTASHOP_ROOT_DIR=${OPENSHIFT_DATA_DIR}public;

cd $OPENSHIFT_DATA_DIR;
if [ ! -d ${PRESTASHOP_ROOT_DIR} ]; then
  
  # Create root document for prestashop
  mkdir -p ${PRESTASHOP_ROOT_DIR};

fi

# Get Prestashop and unzip
wget -c https://download.prestashop.com/download/releases/prestashop_${PRESTASHOP_VERSION}_${PRESTASHOP_LANG}.zip; 
unzip prestashop_${PRESTASHOP_VERSION}_${PRESTASHOP_LANG}.zip -d ${PRESTASHOP_ROOT_DIR};

ln -sf ${PRESTASHOP_ROOT_DIR}/prestashop ${OPENSHIFT_REPO_DIR}/php;


if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    exit 5
fi

php ${PRESTASHOP_ROOT_DIR}/prestashop/install/index_cli.php \
    --language=${PRESTASHOP_LANG} \
    --name=${OPENSHIFT_APP_NAME} \
    --db_server=${OPENSHIFT_MYSQL_DB_HOST} \
    --db_name=${OPENSHIFT_APP_NAME} \
    --db_user=${OPENSHIFT_MYSQL_DB_USERNAME} \
    --db_password=${OPENSHIFT_MYSQL_DB_PASSWORD} \
    --domain=${OPENSHIFT_APP_DNS} \
    --email=pub@prestashop.com \
    --password=0123456789

    echo "=================================================="
    echo "  Prestashop admin login: pub@prestashop.com"
    echo "  Prestashop admin password: 0123456789"
    echo "  Don't forget to change your Prestashop admin password!"
    echo "=================================================="

